### ISSUE TITLE
Model for elmo

### ISSUE THREAD

**Issue by sarveshsparab** [blackbbc/NER#2]
Hi @blackbbc ,

Thank you so much for providing me with the required data to learn and understand from your implementation. That was really very helpful.

I have been running your code to build the same model that you would have built.
But for reasons unknown, I am not able to replicate the F1 scores you have mentioned on your git repository.

Could you please send me the trained model on which you had run your tests. Your help would be really appreciated and be insightful in understanding the research paper and your implementation better.

Thanks
Sarvesh
email : sparab@usc.edu

**Comment by blackbbc** [comment]
Hi, I'm sorry, there are some issues with `tf.count_nonzeros()` api, so that the lengths is computed wrong. I have fixed this issue and ran for 1 epoch, which seemed normal. You can pull the latest codes and try again. 

Ps: If the f1 of the val of the first epoch is around 90%, it should be correct.
<img width="255" alt="1epoch" src="https://user-images.githubusercontent.com/6975818/56583443-26511700-660c-11e9-8665-b140542df507.png">
